# Generated by Django 3.1.2 on 2021-03-01 21:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20210225_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opening_Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Price_Range',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='business_owner',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 13, 33, 50, 77460)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 13, 33, 50, 77460)),
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=255)),
                ('banner_image', models.ImageField(upload_to='banners')),
                ('categories', models.TextField()),
                ('description', models.TextField()),
                ('features', models.TextField()),
                ('location', models.TextField()),
                ('location_latitude', models.FloatField()),
                ('location_langitude', models.FloatField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.CharField(max_length=20)),
                ('website_link', models.URLField()),
                ('social_media_link', models.TextField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.business_owner')),
            ],
        ),
    ]
