# Generated by Django 3.1.2 on 2021-03-02 00:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20210301_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Business_Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='business',
            name='location_langitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='location_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='business_owner',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 16, 29, 51, 737231)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 16, 29, 51, 737231)),
        ),
    ]
