# Generated by Django 3.1.2 on 2021-03-16 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20210301_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Social_media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='business',
            old_name='owner',
            new_name='super_owner',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='location',
            new_name='written_address',
        ),
        migrations.RemoveField(
            model_name='business',
            name='location_langitude',
        ),
        migrations.RemoveField(
            model_name='business',
            name='location_latitude',
        ),
        migrations.RemoveField(
            model_name='business',
            name='social_media_link',
        ),
        migrations.AlterField(
            model_name='business_owner',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 21, 32, 41, 291773)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 21, 32, 41, 294775)),
        ),
    ]
