# Generated by Django 3.1.2 on 2021-03-16 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20210315_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_owner',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='business-owner'),
        ),
        migrations.AlterField(
            model_name='business_owner',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 4, 5, 42, 482008)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 4, 5, 42, 490028)),
        ),
    ]
