# Generated by Django 2.2.10 on 2021-07-01 13:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0014_auto_20210316_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_owner',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 18, 33, 51, 957143)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 18, 33, 51, 957143)),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('receipt', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 7, 1, 18, 33, 51, 957143))),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Customer')),
            ],
        ),
    ]
