# Generated by Django 2.2.10 on 2021-07-20 09:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auto_20210701_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Business')),
            ],
        ),
        migrations.AlterField(
            model_name='business_owner',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 14, 6, 54, 408025)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 14, 6, 54, 413029)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 14, 6, 54, 413029)),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.FloatField(default=0)),
                ('credit', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Points_owe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.FloatField(default=0)),
                ('credit', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Customer')),
                ('transaction_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Transaction')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='is_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Customer'),
        ),
    ]
