# Generated by Django 2.2.10 on 2021-07-20 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_auto_20210720_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='membership_level',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='business_owner',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 18, 24, 24, 165835)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 18, 24, 24, 165835)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 18, 24, 24, 165835)),
        ),
    ]
