# Generated by Django 2.2.10 on 2021-07-26 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_auto_20210726_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_owner',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 17, 40, 10, 584759)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 17, 40, 10, 587760)),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='individual_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='transfers',
            field=models.ManyToManyField(null=True, to='application.Transfer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 17, 40, 10, 588761)),
        ),
    ]
