# Generated by Django 2.2.10 on 2021-07-26 20:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_auto_20210726_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('points', models.FloatField()),
                ('FROM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sender', to='application.Account')),
                ('TO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receiver', to='application.Account')),
            ],
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='receiver_account',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='sender_account',
        ),
        migrations.AddField(
            model_name='transfer',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Account'),
        ),
        migrations.AlterField(
            model_name='business_owner',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 1, 30, 9, 695159)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 1, 30, 9, 699179)),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='transfers',
            field=models.ManyToManyField(null=True, to='application.PointTransaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 1, 30, 9, 699179)),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='related_transfers',
            field=models.ManyToManyField(null=True, to='application.Transfer'),
        ),
    ]
