# Generated by Django 2.2.10 on 2021-07-26 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_auto_20210727_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='TYPE',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='business_owner',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 3, 7, 10, 751333)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 3, 7, 10, 755333)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 3, 7, 10, 755333)),
        ),
    ]
