# Generated by Django 2.2.10 on 2021-08-02 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_auto_20210802_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='business_owner',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 15, 30, 36, 657834)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 15, 30, 36, 661840)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 15, 30, 36, 661840)),
        ),
    ]
