# Generated by Django 2.2.10 on 2021-08-02 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0031_auto_20210802_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='organization_no',
            field=models.CharField(default='1541-4541', max_length=15),
        ),
        migrations.AlterField(
            model_name='business_owner',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 16, 14, 49, 757558)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 16, 14, 49, 761560)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 16, 14, 49, 762561)),
        ),
    ]
