# Generated by Django 2.2.10 on 2021-08-04 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_auto_20210802_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_block',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='business_owner',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 22, 4, 59, 359714)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 22, 4, 59, 359714)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 22, 4, 59, 359714)),
        ),
    ]
