# Generated by Django 2.2.10 on 2021-09-09 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0034_auto_20210909_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_receiver',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='business_owner',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 9, 22, 10, 54, 951292)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registered_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 9, 22, 10, 54, 955294)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 9, 22, 10, 54, 955294)),
        ),
    ]
